name: Sync to Hugging Face hub

on:
  push:
    branches: [master]

  # to run this workflow manually from the Actions tab
  
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push to hub
        env:
          emotion-app: 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
        run: git push --force https://AkarshS:$emotion-app@huggingface.co/spaces/AkarshS/emotion-app main
